version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: deckmind/server:latest
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Bind-mount host projects and workspaces into the container
      - ${PROJECTS_ROOT_HOST:-/ABSOLUTE/PATH/TO/PROJECTS}:/host/projects
      - ${WORKSPACES_DIR_HOST:-./.workspaces}:/host/workspaces
      # Mount agent home directories for credential access (Claude requires rw access to home)
      - ./agent-homes:/agent-homes:ro
    ports:
      - "8088:8088"
    env_file:
      - server/.env
    environment:
      - CLAUDE_AGENT_IMAGE=deckmind/claude-agent:latest
      - CODEX_AGENT_IMAGE=deckmind/codex-agent:latest
      - GEMINI_AGENT_IMAGE=deckmind/gemini-agent:latest
      - PROJECTS_ROOT=/host/projects
      - WORKSPACES_DIR=/host/workspaces
      - AGENT_HOMES_ROOT=/agent-homes
      - PROJECTS_ROOT_HOST=${PROJECTS_ROOT_HOST}
      - WORKSPACES_DIR_HOST=${WORKSPACES_DIR_HOST}
      # This is the absolute path to your agent homes from outside the docker host
      - AGENT_HOMES_ROOT_MOUNT_PATH=${AGENT_HOMES_ROOT_MOUNT_PATH}
      #- DOCKER_HOST=tcp://host.docker.internal:2376
    # Run as root for Docker socket access (development tool)
    user: root