version: '3.9'

services:
  # Build the agent image so the server can launch containers from it.
  agent-image:
    build: ./agent
    image: devagent/agent:latest
    command: ["true"]
    volumes:
      - ./agent-dir:/root

  server:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./server:/app
      - /var/run/docker.sock:/var/run/docker.sock
      # Bind-mount host projects and workspaces into the container
      - ${PROJECTS_ROOT_HOST:-/ABSOLUTE/PATH/TO/PROJECTS}:/host/projects
      - ${WORKSPACES_DIR_HOST:-./.workspaces}:/host/workspaces
    command: sh -c "apk add --no-cache git && npm install && node src/server.js"
    ports:
      - "8088:8088"
    env_file:
      - server/.env
    environment:
      - AGENT_IMAGE=devagent/agent:latest
      - DEFAULT_AGENT_PORT=8080
      - PROJECTS_ROOT=/host/projects
      - WORKSPACES_DIR=/host/workspaces
      - PROJECTS_ROOT_HOST=${PROJECTS_ROOT_HOST}
      - WORKSPACES_DIR_HOST=${WORKSPACES_DIR_HOST}
    depends_on:
      - agent-image
